    <form id="customForm">
    <div class="fieldset">
        <h2 class="legend">Contact Information</h2>
        <p class="required">* Required Fields</p>
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label class="required" for="email"><em>*</em>Email</label>
                    <div class="input-box">
                        <input type="email" spellcheck="false" autocorrect="off" autocapitalize="off" class="input-text required-entry validate-email" value="" title="Email" id="email" name="email">
                    </div>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <button class="button" title="Submit" type="button" onclick="submitForm();"><span><span>Submit</span></span></button>
    </div>
    </form>
<script type="text/javascript">
	function submitForm(){
		//< ![CDATA[
		var customForm = new VarienForm('customForm',false);
		//]]>
		if(customForm.validator && !customForm.validator.validate()) {
	        return;
	    }
		var email = $('email').value;
		new Ajax.Request(
                '<?php echo Mage::getBaseUrl() ?>referandearn/index/submitForm',
                {
                    method:     'POST',
                    parameters: {
	                    email: email,
	                    code: 'code'
                	},
                    onSuccess: function(success){
                    	console.log(success);
                    },
                }
        );
	}
</script>